defaults:
  - default

mesh_explorer:
  _target_: polpo.dash.components.MultiModelsMeshExplorer
  _convert_: object
  graph:
    _target_: polpo.dash.components.Graph
    id_: mesh-plot
    plotter:
      _target_: polpo.plot.mesh.MeshesPlotter
      plotters: ${data:mesh_plotters}
      overlay_plotter:
        _target_: polpo.plot.mesh.StaticMeshPlotter
        mesh: ${data:template_mesh}
      bounds: ${data:bounds}
      overlay_bounds: ${data:template_bounds}
  models:
    - ${model:week_mesh}
    - ${model:hormones_mesh}
  inputs:
    # week
    - _target_: polpo.dash.components.Slider
      var_def: ${var:gestWeek}
    # hormones
    - _target_: polpo.dash.components.ComponentGroup
      ordering: ${var:hormones_ordering}
      components:
        - _target_: polpo.dash.components.Slider
          var_def: ${var:estro}
          step: 500
          label_style:
            fontSize: 30
            display: "block"
        - _target_: polpo.dash.components.Slider
          var_def: ${var:prog}
          step: 3
          label_style:
            fontSize: 30
            display: "block"
        - _target_: polpo.dash.components.Slider
          var_def: ${var:lh}
          step: 0.05
          label_style:
            fontSize: 30
            display: "block"
  checkbox_labels:
    - - -1
      - Show Full Brain
      - false
  postproc_pred:
    _target_: polpo.preprocessing.Pipeline
    steps:
      - _target_: polpo.preprocessing.dict.DictMap
        step:
          _target_: polpo.preprocessing.ListSqueeze
      - _target_: polpo.preprocessing.dict.DictToValuesList

  button_label: Click Here to Toggle Between Gestational Week vs Hormone Value Prediction
