hormones_mesh:
  _target_: polpo.models.SklearnLikeModelFactory
  model:
    _target_: polpo.models.VertexBasedMeshRegressor
    vertex_model:
      _target_: geomstats.learning._sklearn.LinearRegression
  data:
    - ${data:hormones_for_pred}
    - ${data:meshes}
  pipeline:
    _target_: polpo.preprocessing.Pipeline
    steps:
      - _target_: polpo.preprocessing.HashMerger
      - _target_: polpo.preprocessing.NestingSwapper
      - _target_: polpo.preprocessing.IndexMap
        index: 0
        step:
          _target_: polpo.preprocessing.Map
          step:
            _target_: polpo.preprocessing.DictToValues
