defaults:
  - _self_
  # hipp, maternal, multiple
  - data: hipp
  # TODO: make combinatorial; can update structure
  - models: ${data}
  - vars: ${data}
  - objs: ${data}

server:
  debug: false
  use_reloader: false
  host: "0.0.0.0"
  port: "8050"

app:
  assets_folder: ./assets
  title: "herbrain"

style:
  margin_side: 20px
  text_fontsize: 24px
  text_fontfamily: Avenir
  title_fontsize: 40px
  space_between_sections: 70px
  space_between_title_and_content: 30px
