defaults:
  - _self_
  - data
  - models: pca_linreg
  - vars
  - objs

server:
  debug: true
  use_reloader: false
  host: "0.0.0.0"
  port: "8050"

style:
  margin_side: 20px
  text_fontsize: 24px
  text_fontfamily: Avenir
  title_fontsize: 40px
  space_between_sections: 70px
  space_between_title_and_content: 30px

app:
  # assets_folder: ./assets
  title: "herbrain"
