data:
  hormones: # outputs df; may contain None
    _target_: polpo.preprocessing.Pipeline
    steps:
      - _target_: polpo.preprocessing.ssh.ScpDataLoader.from_host_name
        data_dir: ~/.herbrain/data/menstrual
        host_name: frank
        remote_path: /home/data/menstrual/hormones.csv
        recursive: false
      - _target_: polpo.preprocessing.pd.CsvReader
      - _target_: polpo.preprocessing.pd.IndexSetter
        key: dayID

  hormones_for_pred: # outputs dict
    _target_: polpo.preprocessing.Pipeline
    data: ${data:hormones}
    steps:
      - _target_: polpo.preprocessing.pd.ColumnsSelector
        column_names: ${var:hormones_ordering}
      # TODO: check need for this
      - _target_: polpo.preprocessing.pd.Dropna
      - _target_: polpo.preprocessing.pd.DfToDict
        orient: index

  registered_meshes: # outputs dict of meshes (hash is sessionID)
    _target_: polpo.preprocessing.Pipeline
    steps:
      - _target_: polpo.preprocessing.ssh.ScpDataLoader.from_host_name
        data_dir: ~/.herbrain/data/menstrual/registration
        host_name: frank
        remote_path: /home/data/menstrual/meshes_adele/d_reparameterized
        recursive: true
        local_basename: adele
      - _target_: polpo.preprocessing.path.FileFinder
        rules:
          - _target_: polpo.preprocessing.path.FileRule
            value: .ply
            func: endswith
      - _target_: polpo.preprocessing.Sorter
      - _target_: polpo.preprocessing.BranchingPipeline
        branches:
          - _target_: polpo.preprocessing.Map
            step:
              _target_: polpo.preprocessing.Pipeline
              steps:
                - _target_: polpo.preprocessing.path.PathShortener
                - _target_: polpo.preprocessing.str.DigitFinder
                  index: 1
          - _target_: polpo.preprocessing.Map
            step:
              _target_: polpo.preprocessing.mesh.io.TrimeshReader
      - _target_: polpo.preprocessing.dict.Hash
