vars:
  Prog:
    _target_: polpo.dash.variables.VarDef
    name: Progesteron
    unit: ng/ml
    min_value: 0
    max_value: 15
  Estro:
    _target_: polpo.dash.variables.VarDef
    name: Estrogen
    unit: pg/ml
    min_value: 0
    max_value: 250
  LH:
    _target_: polpo.dash.variables.VarDef
    name: LH
    unit: ng/ml
    min_value: 0
    max_value: 50
  DHEAS:
    _target_: polpo.dash.variables.VarDef
    name: DHEAS
    unit: ng/ml
    min_value: 0
    max_value: 300
  FSH:
    _target_: polpo.dash.variables.VarDef
    name: FSH
    unit: ng/ml
    min_value: 0
    max_value: 15
  SHBG:
    _target_: polpo.dash.variables.VarDef
    name: SHBG
    unit: ng/ml
    min_value: 0
    max_value: 70
  hormones_ordering:
    - Prog
    - Estro
    - LH
    - DHEAS
    - FSH
    - SHBG
