defaults:
  - data: data
  - models: models

server:
  debug: true
  use_reloader: false
  host: "0.0.0.0"
  port: "8050"

app:
  assets_folder: /home/luisfpereira/Repos/github/herbrain/project_pregnancy/assets
  title: "herbrain"

style:
  margin_side: 20px
  text_fontsize: 24px
  text_fontfamily: Avenir
  title_fontsize: 40px
  space_between_sections: 70px
  space_between_title_and_content: 30px

variables:
  estro:
    _target_: dash_gi.variables.VarDef
    name: Estrogen
    unit: pg/ml
    min_value: 4100
    max_value: 12400
  prog:
    _target_: dash_gi.variables.VarDef
    name: Progesteron
    unit: ng/ml
    min_value: 54
    max_value: 103
  lh:
    _target_: dash_gi.variables.VarDef
    name: LH
    unit: ng/ml
    min_value: 0.59
    max_value: 1.45
  gestWeek:
    _target_: dash_gi.variables.VarDef
    name: Gestational Week
    min_value: 0
    max_value: 36
    default_value: 15
  EndoStatus:
    _target_: dash_gi.variables.VarDef
    name: Pregnancy status
  trimester:
    _target_: dash_gi.variables.VarDef
    name: Trimester
  sessionID:
    _target_: dash_gi.variables.VarDef
    name: Session Number
    min_value: 1
    max_value: 26
  mri_x:
    _target_: dash_gi.variables.VarDef
    name: X Coordinate (Changes Side View)
  mri_y:
    _target_: dash_gi.variables.VarDef
    name: Y Coordinate (Changes Front View)
  mri_z:
    _target_: dash_gi.variables.VarDef
    name: Z Coordinate (Changes Top View)

mri_explorer:
  id_prefix: mri-
  _target_: dash_gi.components.MriExplorer
  mri_data: ${data:mri}
  hormones_df: ${data:hormones}
  sliders:
    _target_: dash_gi.components.MriSliders
    components:
      - _target_: dash_gi.components.Slider
        var_def: ${var:sessionID}
      - _target_: dash_gi.components.Slider
        var_def: ${var:mri_x}
        step: 5
      - _target_: dash_gi.components.Slider
        var_def: ${var:mri_y}
        step: 5
      - _target_: dash_gi.components.Slider
        var_def: ${var:mri_z}
        step: 5
    trims:
      - - 20
        - 40
      - 50
      - 70
  session_info:
    _target_: dash_gi.components.ComponentGroup
    title: Session Information
    components:
      - _target_: dash_gi.components.DepVar
        var_def: ${var:sessionID}
      - _target_: dash_gi.components.DepVar
        var_def: ${var:gestWeek}
      - _target_: dash_gi.components.DepVar
        var_def: ${var:estro}
      - _target_: dash_gi.components.DepVar
        var_def: ${var:lh}
      - _target_: dash_gi.components.DepVar
        var_def: ${var:EndoStatus}
      - _target_: dash_gi.components.DepVar
        var_def: ${var:trimester}

mesh_explorer:
  _target_: dash_gi.components.MeshExplorer
  week_mesh_model: ${model:week_mesh}
  hormones_mesh_model: ${model:hormones_mesh}
  graph:
    _target_: dash_gi.components.Graph
    id_: mesh-plot
    plotter:
      _target_: dash_gi.plot.MeshPlotter
  hormone_sliders:
    _target_: dash_gi.components.ComponentGroup
    components:
      - _target_: dash_gi.components.Slider
        var_def: ${var:estro}
        step: 500
        label_style:
          fontSize: 30
          display: "block"
      - _target_: dash_gi.components.Slider
        var_def: ${var:prog}
        step: 3
        label_style:
          fontSize: 30
          display: "block"
      - _target_: dash_gi.components.Slider
        var_def: ${var:lh}
        step: 0.05
        label_style:
          fontSize: 30
          display: "block"
  week_sliders:
    _target_: dash_gi.components.Slider
    var_def: ${var:gestWeek}
