week_mesh:
  _target_: polpo.models.SklearnLikeModelFactory
  model:
    _target_: polpo.models.ObjectRegressorWithColors
    model:
      _target_: sklearn.linear_model.LinearRegression
    objs2y:
      _target_: polpo.models.Meshes2Comps
      dim_reduction:
        _target_: sklearn.decomposition.PCA
        n_components: 4
      smoother: false
      mesh_transform:
        _target_: polpo.preprocessing.Map
        step:
          - _target_: polpo.preprocessing.mesh.transform.AffineTransformation
            transform: ${data:affine_transformation}
    colorizer:
      _target_: polpo.models.MeshColorizer
      x_ref:
        _target_: numpy.asarray
        a: 0.5
      delta_lim:
        _target_: numpy.asarray
        a: 15.0
  data:
    - ${data:hormones_gest_week}
    - ${data:registered_meshes}
  pipeline: ${var:session_week_mesh_merger}

hormones_mesh:
  _target_: polpo.models.SklearnLikeModelFactory
  model:
    _target_: polpo.models.ObjectRegressorWithColors
    model:
      _target_: sklearn.linear_model.LinearRegression
    objs2y:
      _target_: polpo.models.Meshes2Comps
      dim_reduction:
        _target_: sklearn.decomposition.PCA
        n_components: 4
      smoother: false
      mesh_transform:
        _target_: polpo.preprocessing.Map
        step:
          - _target_: polpo.preprocessing.mesh.transform.AffineTransformation
            transform: ${data:affine_transformation}
    x2x:
      _target_: polpo.models.X2xPipeline
      scaler:
        _target_: sklearn.preprocessing.StandardScaler
        with_mean: True
        with_std: True
    colorizer:
      _target_: polpo.models.MeshColorizer
      scaling_factor: 2.0
  data:
    - ${data:hormones_for_pred}
    - ${data:registered_meshes}
  pipeline: ${var:session_hormones_mesh_merger}
